import fs from 'fs';
import path from 'path';
// Nota: en un entorno de producción real de Node.js, instalaríamos 'pdf-parse' 
// ejecutando: npm install pdf-parse
// import pdf from 'pdf-parse';

interface ExtractedArticle {
  articleNumber: string;
  title: string;
  content: string;
  startPage: number;
}

/**
 * Script para ingestar y segmentar PDFs de gacetas oficiales en la base de datos de CascoLegal.
 */
export async function processPDFDocument(
  filePath: string,
  docType: string,
  docNumber: string,
  title: string,
  emissionDate: string,
  publicationDate: string,
  gazetteNumber: string,
  officialUrl: string
) {
  console.log(`[Ingestor] Procesando archivo PDF: ${path.basename(filePath)}...`);

  if (!fs.existsSync(filePath)) {
    throw new Error(`El archivo en la ruta ${filePath} no existe.`);
  }

  const fileBuffer = fs.readFileSync(filePath);
  
  // En producción, extraeríamos el texto completo usando la librería pdf-parse:
  // const data = await pdf(fileBuffer);
  // const fullText = data.text;
  
  // Simulación del texto extraído de la Gaceta Oficial para propósitos del MVP:
  const simulatedText = `
    GACETA OFICIAL DIGITAL N° ${gazetteNumber}
    REPÚBLICA DE PANAMÁ, ${publicationDate}
    
    DECRETO EJECUTIVO N° ${docNumber}
    ${title}
    
    CONSIDERANDO:
    Que es deber del Estado regular la seguridad vial de los motociclistas...
    
    DECRETA:
    
    Artículo 1. Todos los conductores de motocicletas deben transitar con precaución.
    
    Artículo 2. Es mandatorio portar la licencia de conducir Tipo B vigente.
    
    Artículo 3. Las motocicletas de delivery deben cumplir con las normas de rotulación de placa en sus contenedores traseros.
    
    Artículo 4. Todo motociclista y acompañante debe usar un casco de seguridad certificado.
  `;

  console.log(`[Ingestor] Texto extraído con éxito. Tamaño: ${simulatedText.length} caracteres.`);
  console.log(`[Ingestor] Segmentando texto en artículos...`);

  const articles = segmentTextIntoArticles(simulatedText);
  console.log(`[Ingestor] Se detectaron ${articles.length} artículos.`);

  // Generamos el SQL de inserción para la base de datos
  const documentId = `doc-${docNumber}-${Date.now().toString().slice(-4)}`;
  
  let sqlQueries = `-- Inserción del documento legal\n`;
  sqlQueries += `INSERT INTO legal_documents (id, doc_type, doc_number, title, emission_date, publication_date, gazette_number, status_vigency, official_url, file_hash, review_status) \n`;
  sqlQueries += `VALUES ('${documentId}', '${docType}', '${docNumber}', '${title}', '${emissionDate}', '${publicationDate}', '${gazetteNumber}', 'pendiente_revision', '${officialUrl}', 'hash-del-pdf', 'pending');\n\n`;

  sqlQueries += `-- Inserción de los artículos segmentados\n`;
  articles.forEach((art, index) => {
    const articleId = `art-${documentId}-${index + 1}`;
    sqlQueries += `INSERT INTO articles (id, document_id, article_number, title, content, start_page, keywords) \n`;
    sqlQueries += `VALUES ('${articleId}', '${documentId}', '${art.articleNumber}', '${art.title}', '${art.content.replace(/'/g, "''")}', ${art.startPage}, ARRAY['${art.articleNumber}', 'autogenerated']);\n`;
  });

  const outputPath = path.join(path.dirname(filePath), `${path.basename(filePath, '.pdf')}_processed.sql`);
  fs.writeFileSync(outputPath, sqlQueries);
  console.log(`[Ingestor] Script SQL generado con éxito en: ${outputPath}`);
  
  return {
    documentId,
    articlesCount: articles.length,
    sqlScriptPath: outputPath
  };
}

/**
 * Divide el texto de una ley en base a expresiones regulares que identifican "Artículo X"
 */
function segmentTextIntoArticles(text: string): ExtractedArticle[] {
  const articles: ExtractedArticle[] = [];
  
  // Expresión regular para buscar "Artículo 1", "Artículo 2", etc.
  const articleRegex = /Artículo\s+(\d+)\.?\s*([\s\S]*?)(?=(?:Artículo\s+\d+\.?)|$)/gi;
  
  let match;
  while ((match = articleRegex.exec(text)) !== null) {
    const num = match[1];
    const rawContent = match[2].trim();
    
    // Extraemos la primera línea del contenido como un título provisional
    const lines = rawContent.split('\n');
    const title = lines[0].slice(0, 80) || `Artículo ${num}`;
    
    articles.push({
      articleNumber: num,
      title: title,
      content: `Artículo ${num}. ${rawContent}`,
      startPage: 1 // Simplificado para el MVP
    });
  }

  return articles;
}
